---
title: "SIR Testing"
author: "Graham Casey Gibson"
date: "5/28/2020"
output:
  html_document: default
  pdf_document: default
---


Stochastic Simulation
```{r}
library(EpiEstim)
library(ggplot2)
data(Flu2009)
## incidence:
head(Flu2009$incidence)

library(incidence)
plot(as.incidence(Flu2009$incidence$I, dates = Flu2009$incidence$dates))

Flu2009$incidence$I <- Flu2009$incidence$I*1000
res_parametric_si <- estimate_R(Flu2009$incidence, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = 2.6, 
                                  std_si = 1.5))
)

plt_original <- plot(res_parametric_si, legend = FALSE)

```



# Suppose we have constant testing. 

```{r,echo='false',results='hide',fig.show='hide'}
library(EpiEstim)
library(ggplot2)
data(Flu2009)
## incidence:
head(Flu2009$incidence)

library(incidence)
plot(as.incidence(Flu2009$incidence$I, dates = Flu2009$incidence$dates))

Flu2009$incidence$I <- Flu2009$incidence$I*.2*1000
res_parametric_si <- estimate_R(Flu2009$incidence, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = 2.6, 
                                  std_si = 1.5))
)
plt <- plot(res_parametric_si, legend = FALSE)

plt_uniform_testing <- plot(res_parametric_si, legend = FALSE)

```

# Suppose we slowly increase testing



```{r,results='hide',fig.show='hide'}
library(EpiEstim)
library(ggplot2)
data(Flu2009)
## incidence:
head(Flu2009$incidence)

library(incidence)
plot(as.incidence(Flu2009$incidence$I, dates = Flu2009$incidence$dates))

Flu2009$incidence$I <- Flu2009$incidence$I*1000*seq(.1,.5,length.out=length(Flu2009$incidence$I))
res_parametric_si <- estimate_R(Flu2009$incidence, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = 2.6, 
                                  std_si = 1.5))
)
plt <- plot(res_parametric_si, legend = FALSE)

plt_variable_testing <- plot(res_parametric_si, legend = FALSE)

```



```{r}
print ("Original")
plot(plt_original$grobs$R)
print ("Uniform Testing")
plot(plt_uniform_testing$grobs$R)
print ("Variable Testing")
plot(plt_variable_testing$grobs$R)
```


```{r}

Flu2009$incidence$I <- Flu2009$incidence$I*1000*runif(length(Flu2009$incidence$I),0.1,.5)
res_parametric_si <- estimate_R(Flu2009$incidence, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = 2.6, 
                                  std_si = 1.5))
)
plt <- plot(res_parametric_si, legend = FALSE)
plot(plt$grobs$R)

```